version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/dockeruser/project
      - gems:/usr/local/bundle
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - postgres
    stdin_open: true
    tty: true
    env_file: .env
    ports:
      - 3000:3000
  postgres:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./:/home/dockeruser/project
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
volumes:
  gems:
